type User {
    id: Int
    login: String
    avatar_url: String
    tasks: [Task]
}

type Task {
    title: String
    description: String
}

type Query {
    findOrCreateUser(login: String): User
}
